version: '3.3'
services:
    flask:
        restart: always
        build:
            context: backend/
        container_name: teccid-flask
        ports:
            - 5000:5000
        volumes:
            - ./backend/:/teccid-api
        env_file:
            - .env

    web:
        restart: always
        image: tec-cid_web:${NG_ENV}
        build: 
            context: frontend/tec-cid/
            args:
                env: ${NG_ENV}
                base_href: ${NG_BASE_HREF}
        ports:
            - "3000:80"
        volumes:
            - /app/node_modules
            - .:/app
