version: '3.3'
services:
    neo4j:
        restart: always
        container_name: teccid-neo4j
        image: neo4j:3.5
        ports: 
            - 7474:7474
            - 7473:7473
            - 7687:7687
        volumes:
            - ./database/conf:/conf
            - ./database/data:/data
            - ./database/import:/import
            - ./database/plugins:/plugins
        env_file:
            - .env

    flask:
        restart: always
        build:
            context: back-end/
        container_name: teccid-flask
        ports:
            - 5000:5000
        volumes:
            - ./back-end/:/app
        depends_on:
            - neo4j
        env_file:
            - .env

