version: '3.3'
services:
    neo4j:
        restart: always
        container_name: teccid-neo4j
        image: neo4j:3.5
        ports: 
            - 7474:7474
            - 7473:7473
            - 7687:7687
        volumes:
            - ./database/conf:/conf
            - ./database/data:/data
            - ./dados:/import
            - ./database/plugins:/plugins
            - ./database/feed:/feed
        env_file:
            - .env

    flask:
        restart: always
        build:
            context: backend/
        container_name: teccid-flask
        ports:
            - 5000:5000
        volumes:
            - ./backend/:/teccid-api
        env_file:
            - .env

    web:
        restart: always
        image: tec-cid_web:${NG_ENV}
        build: 
            context: frontend/tec-cid/
            args:
                env: ${NG_ENV}
                base_href: ${NG_BASE_HREF}
        ports:
            - "3000:80"
        volumes:
            - /app/node_modules
            - .:/app
