version: '3.3'
services:
    neodb:
        restart: always
        container_name: teccid-neodb
        image: neo4j:3.5.7
        ports: 
            - 7474:7474
            - 7473:7473
            - 7687:7687
        volumes:
            - /storage/neo4j/data:/data
            - /storage/neo4j/import:/storage/neo4j/import
            - /var/lib/neo4j/plugins:/var/lib/neo4j/plugins
            - /usr/share/neo4j/lib:/usr/share/neo4j/lib
            - /etc/neo4j:/conf
        env_file:
            - .env
    flask:
        restart: always
        build: .
        image: teccid-flask-image:tag
        container_name: teccid-flask
        ports:
            - 5000:5000
        volumes:
            - .:/app
        depends_on:
            - neodb



